# Stale bot config https://github.com/apps/stale

# Number of days of inactivity before an issue becomes stale (6 months)
daysUntilStale: 183

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because no activity has
  occurred in the last 6 months. It will be closed if no activity occurs in the
  next 30 days. If this issue should not be closed please add a comment.
  Thank you for your understanding and contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed because no activity has occurred in the last 7
  months. Please reopen if this issue should not have been closed. Thank you
  for your contributions.
